color = ''
project-name = 'default'
[default]
account_id = 'acct_1QwqbvBlm5Mx4Vem'
device_name = 'GAGANs-MacBook-Pro.local'
display_name = 'moonlite-test'
live_mode_api_key = 'rk_live_***********************************************************************************************dBmd'
live_mode_key_expires_at = '2025-06-04'
live_mode_pub_key = 'pk_live_51QwqbvBlm5Mx4VemIXbZULuuCLateCKwobygL00YrqAio4lIJfmVCfzQzmFCsTVfySuvY0lwiVHtI7l6ags9c0Pw00omvX8p07'
test_mode_api_key = 'rk_test_51QwqbvBlm5Mx4Vem9q8EEcThmYeZo3uTF6QIkIEM8mHlT8oOIzTKGMYStI2BTYNhT9hIXwWb5aJiqVd3fj1bvcxH00wOI5yhCa'
test_mode_key_expires_at = '2025-06-04'
test_mode_pub_key = 'pk_test_51QwqbvBlm5Mx4VemEZ9AXlDjhYrsI1BdgGNMddUhku3JL34T9cOVJTGFWJ0adYrbeEO7Y3HRbk7qW5vTh6t9fs5G00zqdw75Bw'

