# Reload tmux config
unbind r
bind-key r source-file ~/.config/tmux/tmux.conf 

# Improve colors
# set -g default-terminal '${TERM}'

# change prefix key
unbind-key C-b
set -g prefix C-Space
bind C-Space send-prefix

# turn on mouse controls
set -g mouse on

# act like vim
set -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# create new panesw with the same directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Start pane indexing from 1
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on


# List of plugins
# set -g @plugin 'catppuccin/tmux'
# set -g @plugin "arcticicestudio/nord-tmux"
# set -g @plugin 'dracula/tmux'
# set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vin-tmux-navigator'

set -g @tokyo-night-tmux_transparent 1
set -g @tokyo-night-tmux_show_path 1
set -g @tokyo-night-tmux_path_format relative

# set -g @dracula-show-powerline true
# set -g @dracula-show-flags true
# set -g @dracula-show-left-icon session

# Configure the catppuccin plugin
# set -g @catppuccin_flavor "mocha"
# set -g @catppuccin_window_status_style "rounded"

# Load catppuccin
# run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
# For TPM, instead use `run ~/.config/tmux/plugins/tmux/catppuccin.tmux`

# Make the status line pretty and add some modules
# Main status line background and text color
set -g status on
set -g status-interval 5
set -g status-position top
set -g status-justify centre

# === Global Status Line Style ===
set -g status-style fg=#D8DEE9,bg=#191d24

# === Status Left ===
set -g status-left-length 40
set -g status-left "#[fg=#191d24,bg=#88C0D0,bold] #(tmux display -p '#S' | tr '[:lower:]' '[:upper:]') #[fg=#88C0D0,bg=#191d24,nobold]"

# === Status Right ===
set -g status-right-length 100
set -g status-right "#[fg=#2e3440,bg=#191d24]#[bg=#2e3440,fg=#c0c8d8] #(uptime | awk -F'load averages?: ' '{ print \$2 }') #[default]"

# === Window List ===
set -g window-status-separator ""

# Inactive tabs
set -g window-status-style fg=#D8DEE9,bg=#191d24
set -g window-status-format " #[fg=#D8DEE9]#I:#W #[default]"

# Active tab
set -g window-status-current-format "#[fg=#81A1C1,bg=#191d24]#[fg=#191d24,bg=#81A1C1,bold] #I:#W #[fg=#81A1C1,bg=#191d24]"
set -g window-status-current-style fg=#191d24,bg=#81A1C1,bold

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'


# keep this after the run tpm line. 
set -g status-bg default
# set -g status-style bg=default
